### ISSUE TITLE
Investigate Mongo+Heroku Scalability

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/Site-Sonar-Dashboard#30]
In order to release this to the world, we probably want to make sure that our stack will scale. We should determine whether heroku+mongo is a scalable solution, and how we might scale most effectively when we release.

**Comment by purukaushik** [comment]
Marking [this](https://blog.hartleybrody.com/scale-load/) here.

**Comment by purukaushik** [comment]
Another [article](https://www.compose.com/articles/sizing-and-trimming-your-mongodb/)
