### ISSUE TITLE
Counts on dashboard differ between networksbyfilesize and networksbyloadtime endpoints

### ISSUE THREAD

**Issue by purukaushik** [FrancescoSTL/Site-Sonar-Dashboard#33]
SiteScout has count=5 on [networks by load time site](http://www.ultra-lightbeam.com/networksbyloadtime) but =1 on [networks by file size](http://www.ultra-lightbeam.com/networksbyfilesize)

**Comment by FrancescoSTL** [comment]
Reason turned out to be due to requests which had a filesize of `null` or `0` (redirects, 204s, etc)
