### ISSUE TITLE
Individual Reports for Each Network/Site

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/Site-Sonar-Dashboard#40]
We'd like to have individual reports for each network+website so that you can break down metrics further than what we're currently reporting.

**Comment by purukaushik** [comment]
Click on a network byfilesize/byloadtimes, you get 
1. Histograms for load time and filesize
Click on sites byfilessize/loadtime, you get
1. Group ad networks on site + Aggregate average 
2. radio button to switch between filesize/loadtime

**Comment by FrancescoSTL** [comment]
Update: We're not going to drill down by site because we're removing site dashboards for now. The logic behind this is that we're trying to publish content about ad networks and we don't want to shame site owners in the meantime. We will still collect the data, but as for aggregating it, we'll remove that part for now

**Comment by purukaushik** [comment]
@FrancescoSTL I was thinking about this for network stats page

# Network: Microsoft

| # Assets | Average file size | Average load time |
| --- | --- | --- |
| 403 | 20.166 KB | 360 ms |

| AssetType | Average File Size | Average Load time | #assets |
| --- | --- | --- | --- |
| object_subrequest | 40 KB | 700 ms | 3 |
| sub_frame | 33 Bytes | 20 ms | 400 |

Histogram 1

Histogram 2

**Comment by FrancescoSTL** [comment]
@purukaushik Cool, this looks good. I think that # assets, avg file size, and TTFB should be outside of a table, but we can work on that while upgrading front-end stuff later.

**Comment by purukaushik** [comment]
classic :ok_hand:

**Comment by purukaushik** [comment]
@FrancescoSTL 
This look good for site specific stats ?

## Site: hooli.com

| Ad Network | Average File Size | Average Load Time | # Assets |
| --- | --- | --- | --- |
| google | 200 KB | 500 ms | 25 |
| linkedin | 700 KB | 200 ms | 35 |

| AssetType | Average File Size | Average Load Time | #Assets |
| --- | --- | --- | --- |
| image | 500 KB | 100 ms | 30 |
| media | 1000 KB | 200 ms | 30 |

**Comment by FrancescoSTL** [comment]
@purukaushik can we also add the histograms and overall data like we do in the network page? Like # assets logged, total file size, average TTFB, and then the two histograms

**Comment by FrancescoSTL** [comment]
@purukaushik and being that we've got limited vertical space, I'd limit the Networks to top 5 networks by asset count. Prolly sort everything descending by asset count
