### ISSUE TITLE
Rename Network Load Time to TTFB

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/Site-Sonar-Dashboard#44]
I believe the measurement we're actually grabbing when we say "network response time" is TTFB or, the time it takes for the network to respond with the first byte of information back from the server. 

So far as I understand it, TTFB can be calculated by taking (onHeaderSent time - onHeaderRecieved time), which is what we're currently doing. Is this correct @digitarald?

**Comment by digitarald** [comment]
Makes sense to me

**Comment by FrancescoSTL** [comment]
Done.
