### ISSUE TITLE
Add Main Dashboard Page

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/Site-Sonar-Dashboard#56]
We'd like a dashboard overview page with similar numbers to the overview in the add-on:
1. Cumulative network time
2. Sum of all file sizes
3. Count of all ad-assets benchmarked

**Comment by purukaushik** [comment]
Total assets
Sum of all asset load times
Sum of all file sizes

**Comment by purukaushik** [comment]
This is how it looks now
<img width="1798" alt="screen shot 2016-09-07 at 12 41 05 pm" src="https://cloud.githubusercontent.com/assets/5105099/18325942/709152e2-74f8-11e6-8e00-457a849d43ec.png">

**Comment by FrancescoSTL** [comment]
Ayyee fam
