### ISSUE TITLE
Can't Access Resources

### ISSUE THREAD

**Issue by FrancescoSTL** [FrancescoSTL/Site-Sonar-Dashboard#8]
Looks like there may have been some errors introduced in the last PR. We're getting Internal Server Error's (500 response) from various bootstrap assets.

<img width="751" alt="screen shot 2016-08-02 at 5 26 08 pm" src="https://cloud.githubusercontent.com/assets/9794516/17349881/6d3d2ee2-58d6-11e6-9848-ae6f7d892c1a.png">

**Comment by purukaushik** [comment]
![relative references](https://i.imgflip.com/18cxf5.jpg)

**Comment by FrancescoSTL** [comment]
Still referencing a bunch of stuff which isn't there @justinpotts :

<img width="1625" alt="screen shot 2016-08-06 at 2 05 29 pm" src="https://cloud.githubusercontent.com/assets/9794516/17459050/e414d514-5bde-11e6-8bc1-03352460ec52.png">

**Comment by justinpotts** [comment]
Fixed @FrancescoSTL 👌

![fixed](https://cloud.githubusercontent.com/assets/2042849/17459685/9038ed5e-5bf7-11e6-96b1-5cb00ea2295c.gif)
